### ISSUE TITLE
white bar at ios 8.4

### ISSUE THREAD

**Issue by qiyadeng** [wangruofeng/RFSegmentView#3]
It works ok at ios 9.0,but it only dispear an whte bar in ios 8.4?

**Comment by dashi001** [comment]
在layoutSubviews方面里面修改
//configure bgView
    self.bgView.frame = CGRectMake(leftRightMargin, (viewHeight - self.itemHeight?:kItemHeight)/2, viewWidth - 2_kLeftRightMargin, self.itemHeight?:kItemHeight);
    /_*
     \*  在初始化label的rect之前，给itemWidth、itemHeight重新赋值，保证iOS7能正常显示
     */
    itemWidth = CGRectGetWidth(self.bgView.frame)/count;
    itemHeight = CGRectGetHeight(self.bgView.frame);

```
//configure items
[self.items enumerateObjectsUsingBlock:^(RFSegmentItem * _Nonnull item, NSUInteger idx, BOOL * _Nonnull stop) {
    item.frame = CGRectMake(initX, initY, itemWidth, itemHeight);
    initX += itemWidth;
}];
```

**Comment by wangruofeng** [comment]
尝试最新版本，UI布局异常的bug已经修复
